Python: include cleanup, move casadi function generation in one file
acados/acados pull request #892
Opened 2022-11-30 16:06 UTC by FreyJo

2022-12-01 13:55 UTC, sandmaennchen requested changes
could you order the functions in `casadi_function_generation.py`? :upside_down_face:

2022-12-01 13:55 UTC, sandmaennchen commented on examples/acados_python/rsm_example/main.py
> +# np = model.p.size()[0]
just remove this line?

2022-12-01 14:36 UTC, FreyJo commented on examples/acados_python/rsm_example/main.py
> +# np = model.p.size()[0]
Done!

2022-12-01 14:36 UTC, FreyJo commented
All addressed!

2022-12-02 09:00 UTC, sandmaennchen approved these changes
:+1:

2022-12-02 09:00 UTC, merged